version: "3.9"
services:

  worker:
    build:
      context: ./Worker
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    
  manager:
    container_name: manager
    build:
      context: ./Manager
      dockerfile: ./Dockerfile
      args:
        NUM: 1
    ports:
      - "8080:8080"